//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarFinderSvc.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string id { get; set; }
        public Nullable<int> make_id { get; set; }
        public string model { get; set; }
        public string trim { get; set; }
        public string year { get; set; }
        public Nullable<int> bodystyle_id { get; set; }
        public Nullable<int> engine_position_id { get; set; }
        public string engine_cc { get; set; }
        public string engine_cyl { get; set; }
        public Nullable<int> engine_type_id { get; set; }
        public string engine_valves_per_cyl { get; set; }
        public string engine_power_ps { get; set; }
        public string engine_power_rpm { get; set; }
        public string engine_torque_nm { get; set; }
        public string engine_torque_rpm { get; set; }
        public string engine_bore_mm { get; set; }
        public string engine_stroke_mm { get; set; }
        public string engine_compression { get; set; }
        public Nullable<int> engine_fuel_id { get; set; }
        public string top_speed_kph { get; set; }
        public string zero_to_100_kph { get; set; }
        public Nullable<int> drive_id { get; set; }
        public Nullable<int> transmission_type_id { get; set; }
        public string seats { get; set; }
        public string doors { get; set; }
        public string weight_kg { get; set; }
        public string length_mm { get; set; }
        public string width_mm { get; set; }
        public string height_mm { get; set; }
        public string wheelbase_mm { get; set; }
        public string lkm_hwy { get; set; }
        public string lkm_mixed { get; set; }
        public string lkm_city { get; set; }
        public string fuel_cap_l { get; set; }
        public string sold_in_us { get; set; }
        public string co2 { get; set; }
        public string make_display { get; set; }
    
        public virtual BodyStyle BodyStyle { get; set; }
        public virtual DriveType DriveType { get; set; }
        public virtual EngineFuel EngineFuel { get; set; }
        public virtual EnginePosition EnginePosition { get; set; }
        public virtual EngineType EngineType { get; set; }
        public virtual Make Make { get; set; }
        public virtual TransmissionType TransmissionType { get; set; }
    }
}
